name: Docusaurus deploy to gh-pages CI

on:
  push:
    branches: [master-src]
  pull_request:
    branches: [master-src]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: website

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}
          git remote set-url origin https://github.com/${{ secrets.USERNAME }}/${{ secrets.REPO }}.git
          npm run predeploy
        working-directory: ${{env.working-directory}}
      - name: Deploy to gh-pages
        run: npm run deploy --if-present
        working-directory: ${{env.working-directory}}
        env:
          CI: true
